CREATE TABLE IF NOT EXISTS BookExibitionV1(Id INT PRIMARY KEY AUTO_INCREMENT, PersonIdentifier VARCHAR(15),
BookName1 NVARCHAR(50), Author1 NVARCHAR(50), Publisher1 NVARCHAR(50),
BookName2 NVARCHAR(50), Author2 NVARCHAR(50), Publisher2 NVARCHAR(50),
BookName3 NVARCHAR(50), Author3 NVARCHAR(50), Publisher3 NVARCHAR(50),
BookName4 NVARCHAR(50), Author4 NVARCHAR(50), Publisher4 NVARCHAR(50),
BookName5 NVARCHAR(50), Author5 NVARCHAR(50), Publisher5 NVARCHAR(50),
) ENGINE=INNODB;

INSERT INTO BookExibitionV1